name: gotruhub

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - name: Create .env file
      run: |
        touch .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "TOKEN_KEY=${{ secrets.TOKEN_KEY }}" >> .env
        echo "username=${{ secrets.username }}" >> .env
        echo "pass=${{ secrets.pass }}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
        echo "AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .env
        echo "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" >> .env
        echo "PROJ_ENV=${{ secrets.PROJ_ENV }}" >> .env
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
        echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> .env
        echo "EC2_USERNAME=${{ secrets.EC2_USERNAME }}" >> .env
        echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}" >> .env
        
    - name: install dependencies
      run: npm install
     
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   steps:
  #   - name: SSH into EC2 and deploy
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.EC2_HOST }}
  #       username: ${{ secrets.EC2_USERNAME }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       script: |
  #         cd tracaBE
  #         git pull 
  #         export NVM_DIR=~/.nvm
  #         source ~/.nvm/nvm.sh
  #         npm run build
  #         npm run start_dev